refactor(pre-commit): cleaned up code and indent

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -2,9 +2,7 @@
 # Pre-commit hook to run make all
 
 echo "Running 'make all'..."
-make all
-
-if [ $? -ne 0 ]; then
-    echo "'make all' failed. Commit aborted."
-    exit 1
+if ! make all; then
+  echo "'make all' failed. Commit aborted."
+  exit 1
 fi
